### ISSUE TITLE
Pool usage metrics

### ISSUE THREAD

**Issue by christianang** [telekom/cluster-api-ipam-provider-in-cluster#112]
It would be useful if we could some usage statistics from the pool without having to query the IPAddresses and count ourselves.

We are thinking of adding a total, used, free in the pool status. E.g.

```yaml
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: pool-name
  namespace: pool-ns
spec:
  subnet: 10.0.0.0/24
status:
  ipAddresses:
    # The total number of IPs the pool has.
    total: 255
    # The number of IPs that have already been allocated.
    used: 9
    # The number of IPs that are available to allocate.
    free: 250
```
