### ISSUE TITLE
Feature Request: Ability to configure the pool with a list of non-contiguous IP addresses

### ISSUE THREAD

**Issue by tylerschultz** [telekom/cluster-api-ipam-provider-in-cluster#21]
Feature Request:

We have a case where we're not able to obtain a contiguous block of IP addresses. We can, however, get a set of IPs that are on the same network. We'd like the ability to configure the pool with this list of IP. 

We propose being able to set a list of IP in place of a CIDR or start & end:

```
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: inclusterippool-sample
spec:
  prefix: 24
  gateway: 10.0.0.1
  addresses:
    - 10.0.0.5
    - 10.0.0.7
    - 10.0.0.9
    - 10.0.0.14
    - 10.0.0.6
```

It seems some validations would be prudent too, to ensure the IPs are within the gateway/prefix range.

cc @adobley @flawedmatrix @christianang

**Comment by tylerschultz** [comment]
If this feature request is reasonable/acceptable to the powers that be, we would like to contribute the implementation. 
Is more discussion needed?

**Comment by schrej** [comment]
Sorry, somehow missed this one. Sounds reasonable, go for it!

**Comment by tylerschultz** [comment]
Hi @schrej, we think we found an inconsistency in the behavior of First and Last.

Suppose the pool spec were to look something like this:
```
spec:
  prefix: 24
  subnet: 10.0.0.0/24
```
First and Last would be [defaulted](https://github.com/telekom/cluster-api-ipam-provider-in-cluster/blob/main/internal/webhooks/inclusterippool.go#L68-L73) to 10.0.0.1 and 10.0.0.254. 
The [FindFreeAddress function calls .Next()](https://github.com/telekom/cluster-api-ipam-provider-in-cluster/blob/main/internal/poolutil/pool.go#L61) on the first IP in the range and the first ip provided would be 10.0.0.2. This seems good, the gateway is typically the 10.0.0.1. 
Side note: it could be another address in the range. (citation needed)
The last address (10.0.0.254) would never be provided [because the guard](https://github.com/telekom/cluster-api-ipam-provider-in-cluster/blob/main/internal/poolutil/pool.go#L67) prevents the last address from being provided. We assume the intention was not to provide the 255 address, but we aren't sure.

Next lets consider when the user specifies First and Last:
```
spec:
  prefix: 24
  subnet: 10.0.0.0/24
  first: 10.0.0.10
  last: 10.0.0.15
```
First and last would not be defaulted and would stay as specified.
The FindFreeAddress() function would first try First.Next() resulting 10.0.0.11. The code would never return 10.0.0.15 because of the guard that prevents the last address from being provided.

We propose that we change the logic so that the First and Last be provided. The only exceptions being that First or Last was the network address (10.0.0.0), the gateway address (10.0.0.1 or whatever was provided), or the broadcast address (10.0.0.255). This would be a significant change in the behavior, so we'd like to hear if you think this would be problematic. Hopefully that makes sense.
