### ISSUE TITLE
Cluster API with IPAM & InCluster compatibility

### ISSUE THREAD

**Issue by ErikLundJensen** [telekom/cluster-api-ipam-provider-in-cluster#53]
It looks like we are trying to solve the same issues related to IP address management at vSphere using Kubernetes Cluster API.

Is this component working with CAPV v1.5.1 and Cluster API 1.3.1 ?

Given the following template with reference to the cluster IP pool using the new feature "addressesFromPools" in CAPV 1.5.0:
```

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: vmware-test-controlplane
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: dc1
      datastore: datastore5
      diskGiB: 10
      folder: vmware-test
      memoryMiB: 8192
      network:
        devices:
        - dhcp4: false
          dhcp6: false
          gateway4: 192.168.0.1
          addressesFromPools:
          - apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: vmware-test-controlplane
          networkName: VM Network
     ...
```
and the IPAM:
```
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: vmware-test-controlplane
spec:
  start: 192.168.5.10
  end: 192.168.5.14
  prefix: 24
  gateway: 192.168.0.1
```
From those configuration we do get IPAddresses and IPAddressclaims as expected, however, the IP are not propagated to the virtual machine.
I wonder if `cluster-api-ipam-provider-in-cluster` was written before the release of CAPV 1.5.0 and thereby not being compatible with the new CAPV feature.

Note, we are using Talos for bootstrap & control plane, however, that should not affect IPAM.
