### ISSUE TITLE
Proposal: Cross-Namespace Pools

### ISSUE THREAD

**Issue by adobley** [telekom/cluster-api-ipam-provider-in-cluster#54]
Currently an InClusterIPPool is per namespace. We would like to have the ability to define a single pool of IPs that can fulfill claims for clusters in various namespaces.

Right now it is possible to define the same pool in multiple namespaces and get the behavior of a shared pool. This has the overhead of maintaining that same resource in multiple namespaces. When changing the size of the pool all instances would need to be updated or risk configuration drift.

We propose adding a reference field to the `InClusterIPPool` resource called `poolPointer` which would be an [ObjectReference](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-reference/).

Using CAPV as an example users would create a template in the same way as before:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  name: example
  namespace: cluster-ns
spec:
  template:
    spec:
      cloneMode: FullClone
      numCPUs: 8
      memoryMiB: 8192
      diskGiB: 45
      network:
        devices:
        - dhcp4: false
          fromPool:
            group: ipam.cluster.x-k8s.io/v1alpha1
            kind: InClusterIPPool
            name: my-pool-pointer
```

Create the pool pointer:
```
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: my-pool-pointer
  namespace: cluster-ns
spec:
  poolPointer:
    - name: my-pool
      namespace: pool-ns
      kind: InClusterIPPool
```

Create the pool:
```
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: my-pool
  namespace: pool-ns
spec:
  pools:
    - subnet: 10.10.10.0/24
      start: 10.10.10.100
      end: 10.10.10.200
```

For pools that have a `poolPointer` the controller will need be updated to resolve the IPPool data from the provided namespace/name pool.

The webhook for `InClusterIPPool` should reject any resources that provide both `pools` and `poolPointer`.

`IPAddresses` are already created in the namespace of the `IPAddressClaim` and the controller currently lists `IPAddresses` from all namespaces when determining what IP to assign based on the `kind/name` of the pool.

We're happy to implement this and are looking for feedback on our proposed approach.

cc/ @tylerschultz @flawedmatrix @christianang

**Comment by schrej** [comment]
There might be a small misconception here: If you define the same pool in multiple namespaces, you don't get a _shared_ pool. You get _identical, separate_ pools, meaning that the same IP can be allocated once for each pool. If you deploy your clusters in a shared network, that will lead to IP address collisions.

I guess that's not the intention, and that you want proper shared pools, where each address is only allocated once?

If that's the case, what you've proposed would basically lead to the `my-pool-pointer` acting as a kind of reverse proxy to `my-pool`. For each IPAddressClaim that references `my-pool-pointer` the controller would create another IPAddressClaim that references `my-pool` in the correct namespace, and then mirror the created IPAddress to the namespace of `my-pool-pointer`.
Or at least that's the simplest implementation I can come up with.

Alternatively we could also consider having an annotation on IPAddressClaims that specifies the namespace of the pool (since the claim itself intentionally doesn't allow to set the namespace). That would then require telling the shared pool which namespaces it should fetch IPAddresses from to determine which addresses are already allocated.

**Comment by adobley** [comment]
If you declare two pools with the same name in multiple namespaces you do get a shared pool. Maybe this is a bug or unintended feature.

For example, I declared a pool `my-pool` in two namespaces with a start/end of `10.0.0.10-10.0.0.11` so that there are only two IPs available.

Then I wrote three claims, two in one namespace, one in another. Only two are able to be fulfilled.
```
$ kubectl get inclusterippool,ipaddressclaims,ipaddresses -A
NAMESPACE   NAME                                            SUBNET        FIRST   LAST
one         inclusterippool.ipam.cluster.x-k8s.io/my-pool   10.0.0.0/24
two         inclusterippool.ipam.cluster.x-k8s.io/my-pool   10.0.0.0/24

NAMESPACE   NAME                                                POOL NAME   POOL KIND
one         ipaddressclaim.ipam.cluster.x-k8s.io/first-claim    my-pool     InClusterIPPool
one         ipaddressclaim.ipam.cluster.x-k8s.io/third-claim    my-pool     InClusterIPPool
two         ipaddressclaim.ipam.cluster.x-k8s.io/second-claim   my-pool     InClusterIPPool

NAMESPACE   NAME                                           ADDRESS     POOL NAME   POOL KIND
one         ipaddress.ipam.cluster.x-k8s.io/first-claim    10.0.0.10   my-pool     InClusterIPPool
two         ipaddress.ipam.cluster.x-k8s.io/second-claim   10.0.0.11   my-pool     InClusterIPPool
```

The `third-claim` never gets an IP assigned and we see `failed to find free address: no address available` in the CAIP logs.

It looks like [the ipaddress list call](https://github.com/telekom/cluster-api-ipam-provider-in-cluster/blob/b57d0041bc4a4eddfac7c544899f766267eacac9/internal/poolutil/pool.go#L22) when filtering for IPs searches in all namespaces with a `type/name` key. If you have the same `type/name` across multiple namespaces then it would avoid collisions between these pools.

If this behavior is kept, it does make the solution simpler by avoiding the mirroring behavior described, but maybe this should be opened as a bug? Let me know.

**Comment by schrej** [comment]
That's definitely an oversight and should be considered a bug in my opinion.

But instead of this proxy implementation, we could consider just creating a second custom resource that is identical to InClusterIPPool but cluster-scoped, e.g. GlobalInClusterIPPool or something like it. For that one we could keep ignoring namespaces when fetching IPAddresses.
What do you think?

**Comment by adobley** [comment]
Gotcha!

We chatted a bit about the approaches and settled on the GlobalInClusterIPPool as a better option for ignoring namespaces. For example,
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  name: example
  namespace: cluster-ns
spec:
  template:
    spec:
      cloneMode: FullClone
      numCPUs: 8
      memoryMiB: 8192
      diskGiB: 45
      network:
        devices:
        - dhcp4: false
          fromPool:
            group: ipam.cluster.x-k8s.io/v1alpha1
            kind: GlobalInClusterIPPool
            name: my-pool
```

And the pool:

```
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: GlobalInClusterIPPool
metadata:
  name: my-pool
spec:
  pools:
    - subnet: 10.10.10.0/24
      start: 10.10.10.100
      end: 10.10.10.200
```

Look good?
